---
- secret:
    name: gitea-mirror
    data:
      GITHUB_PAT: !encrypted/pkcs1-oaep
        - Gti1XT1F7r4npN1YNaVpHQzt4Q3yFbSqJNZ5p4hS3pooo53gDRGxAlxOHVi9uFuLu8499
          lF/eYTWpZVORW5kccwM/6YO3u5fDUpNnM5SfVgv4+sBjVo7G/lyyF0mChxAUMNTG2eKQj
          9rC0qV/WA+8haPm0WCjeQ/pkrWeUIs7d7KWnYiw0uPHLStOioXweYsbZlgw9WccKkkJVG
          DXuo9XWbi1Z1eiQZiSCQ8PdBKMbYggIbWlmB6gH9lAiXMjUTsT7FMmmRw9PGE5E9I2Txd
          FsOBSKI4oQMGojkI+OaZu3V0VGGeaIkr7N4WRnc+FZejI2aMMrBs9TZW2tOfEQaP7DMNT
          CQ5UTzdUQIXMv/Hhl5eg98k87kmj0ZN500q9A7YRp8nUqYU0b2n2lQCJt0Q8XDGqVjpJW
          IG/c8QoK89+z7oy/SgSrsw7RGUB97j4O6cK/yI1Aneqn8/3aSbKXF9U8Qcn2SI1qIF/ee
          bB7YwpszXrmhRaTAx0lApdgh0GgeExsUdz1p3MJb3JdBSZap2llAhlVsmIc6x/lheREzZ
          2Bdm12kz+LB+db+SYWpvcVHYUISi9Ddb09RyY/z2ipFvIqv84RtHz/hJUn+cNEzHgcobe
          YKm3chhcza4b2bcFBL/tZeu3ktNmkOjkTUTKGlotXZ7SVUDudQOdPeP9dSdlcM=
      GITEA_TOKEN: !encrypted/pkcs1-oaep
        - Yk8B7CrKvd6hE9FRpqLYhMuoYXSJ29XLOaV3T0JqOmVFP26EywF7ymMkXfrXJPwwyMKgJ
          KQiY9VhppdKRp3ham4KPtWIFx6YTMVvBSrO7ic6jX5sAiQUl/neAvQNLJYyaDU16dG4r3
          hkWYP9dOQ4fanFSk9ZBZrd3mbSzTOXgAdLR+mIy6LgkXnE0RitRUSgspe7a6/ItKIDLwo
          zMK3Ep5MD5uXCbUQLplvZQamBBAtsDS5+H2KJCGbFA7qmm9RGWqZ4XQV7jOdfFXL62hAJ
          wrmbPYMPJDTLjXC0Z1to+RMgi3OyO9D/QHagVvKVQa9AfYZIyyE5Kgv8Bgd23FAifnO57
          AbQVBxRMqpvicqVeivHOcZ1wUehi4pvv+MbTziGvSfmbe9YItHfzlJVnnGswTytJ9oo6q
          PtOphORamVEQ95Pok/v3pAFI0495Y3f4q5LlZAiCsBUgPhnfF8LJ7xDYizDf0CJYjk9n+
          Vt9nrBS7No8718mBYAINFpu2OtkHAFdHgMWCPo0DHMRDWOfA3ypyhoHBwoy25WIe///4I
          9cXI/ebq41zDQVKWaFPpYPVRmRuK/TtL67HGuFRN3rIiza/mMdgDY8Ar2RZAf+2gkVwp7
          CzV41XEVoZjl8B4uLNDFJEkaqkwS4kF747uD73e+tGtqzVDIahTepdxmRBPFoM=
      
- job:
    name: update-gitea-mirrors
    run: .playbooks/update-gitea-mirrors.yaml
    secrets:
      - name: mirror_creds
        secret: gitea-mirror

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - ansible-lint
        - flake8
        - yamllint
    gate:
      jobs:
        - ansible-lint
        - flake8
        - yamllint
    periodic-daily:
      jobs:
        - ansible-lint
        - flake8
        - update-gitea-mirrors
        - yamllint
