---
- secret:
    name: gitea-mirror
    data:
      GITHUB_PAT: !encrypted/pkcs1-oaep
        - b1/eMFfwU59vm0Oxz+RU5Krl1dyLLA6UQXFxHXGi87Wke79JPKIOS7GTIvLv3oE3glCtV
          h94ge1Yy/ffqHhjBOBQfFOIl3btWVRjEteM/wM/xIsBoz3E7AKsKK4NfZR7myhy0Esjdb
          juPaMCn03AZWJbW1h0SPbkQFninIbnCmFMXE/8r4AsgakRPxY5XdPkj4XaWAcatk45fLJ
          zUwLwZBqmgSZmSSUaGsKZs/r1a+blBn6FFufJln9Mc+rEevUpjP9Q8XbhKqouciY+4/u9
          QWKl82p/UJreMd78bOuCPWpQT/Kq10wmhnbjufVSh5T+k5wlkQF1Jf63mtnPGCYpqbsJx
          ThxVqVv2m/OHuxzgVXD/5MqI3SjdHgVx9y3aPZkJ+8D77+VpeyPp+yD3STZ1c+xzSi8TQ
          9g71D1xc3CxaGgNoZ9qb7du2KieqQdHzSDjpia0OdujmdZASca5pGgoXjQsfmXS63CRS7
          StoiMPV/s2Qda+KQuRXX0jYp0hfgOA53X9uxC7wtQORz3KyYHN8HxvPI0mq24/MXASfTG
          VJoU95TWKUOPxTGqDhAsXucLxzpFobh4yx8MqVtMhbuxD+TMKr8Pn7Euail/OWjNVUWzQ
          Ru0FotFJ+PZqZDeV15IqxsZsM7Zo0YSJNa5gtxNY7e+LKMyXUl23pCB4iqENak=
      GITEA_TOKEN: !encrypted/pkcs1-oaep
        - Go/MjB69VVaYOEcZD1Ml1hnEOC0nxOcnP4Ff4zMcr6QKoLd3tFA6ZU2/IffmGvXheTP78
          GWO5o9mmiKlkUxXGK39hPdywwqS9cj8Jwi2AUg3HVc0zDBtt/NEay9GM4agDPqOFknorQ
          qLDWKgDzB44ze7jLquOm+0hWw+EZ4y6X0/cgYoZr806hCEb7y8ha3I41pOQlRtKwT/Dlk
          fs2OKiJz4UudKoLdBmR+pwtCLMsSL8TjJRY6AGVouVhmIUdR+dB0giXID5LYuB+xfJuUh
          MBafHaPO0xz9SwQzi92omHpA+GVB+E9fvsaUnd1lB0gJQfx5wpUQWbwZuMzbinH7KTMV4
          Lcr6p0Eo8KOmetCg3DmoOAdppT9XrvVWOJk3mZ0131G9khbBsH1Vub5uId16mykZGOIGz
          fg2wcqlG1A2XnMhRRBLn4cgehc8LWJHf93Lln6lA4mUZ8E3PltlqNCiCr0ox77XJmxwkp
          mlOz6rOm7xPRUkxhs8eI7nj3zQONqpFCnVIyckoSvxVUxCyIgdqLiQNpP7cX6lg2IwIxu
          If3m+5j2aPCbZfktIj+O8ktTrGQR6HLByGDHWFpbQZ0wRZF3QCFikND6QTqtFDzkAgTTA
          FgZpF1+bwL8BTyJA/hw6qHHGOQAEB19fCWYKr+hXfqP59465FbGdvOjNwuu61c=
      
- job:
    name: update-gitea-mirrors
    run: .playbooks/update-gitea-mirrors.yaml
    secrets:
      - name: mirror_creds
        secret: gitea-mirror

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - ansible-lint
        - yamllint
        - flake8
    gate:
      jobs:
        - ansible-lint
        - yamllint
        - flake8
    periodic-daily:
      jobs:
        - update-gitea-mirrors
