---
- secret:
    name: gitea-mirror
    data:
      GITHUB_PAT: !encrypted/pkcs1-oaep
        - JAy6U3/fVjiQSeKGfK6PypeRQuEf9MLkEZuRjOvyQcXarIfYVTd07EDklunsUahhkM4rn
          VHMqATQwxlo2aqQHAYH51sY5zK6QddKtGaoVraDlkWH/blhQR3J6fr2VvHeThzxifWIi4
          0cPI51Ms8PvshJTrljbBlbRYiA0fm6+y3g1Fwjl1zq381JPsKGg+lEmGC54Lc1bgfz/Mk
          EosQHQ7Fw+syVqwr28N1tyJUiyZ/nuuKJvxgCDCTJqRoJLCs9tmkyps5xcHfaS0ckzCWz
          WGa/0dNH8ai5kDPNNOq/mt8FGm0Y9CEJe+b0mR20HurRVeBRK8CfnZI5v7kROtmW29g97
          G1Uy9F/mWhoF0xHT27+FLjn8GXZjDnLDYTqfDIi3iQ76M0AVNZXHBccMTvDl01Z+r/feM
          pqpdG7ZDBsHTuyJk7Qq390KSHADOn4WqEz/IsIMmXuCxiOp1b5Ukn6+8s4mska4g0rkgC
          wwwB0pWjQa3GEIQmnWbjqdMM8lS2JotuTP5eo3SUlds+Ay/mkziG/q58NfYJSOiyvPFgI
          AvrpBBO2pyWfb2jpQQIR3kS9Gavr/cOm5mGtscDmz/ocEr9fDA52WDdD2ylFooy9VJeqe
          1ufuGhdDryQi+IT/4XQAtFlY4qPdLq7/dcb2nw4qP4W4Qut8xmzqiubiKJT3fU=
      GITEA_TOKEN: !encrypted/pkcs1-oaep
        - GaZmzyM83ZP4slW1f4ddX5rLiuNAdnqjI+K4xTPr2UPJF1HxsI7trkA/8kWYfN6DpzybS
          vISA1dGERtnKbzsf7WVIAt97MyAGnozQVeT50NiQOPf5JR8gddnO2ADZUGGUaURGMb5sR
          zwRvh1PUOosJB9isPH4yQjy2Hw6RLLMP2O3INOR8Fdt0mzXlg1ynWunwcyTnsG6HnNDDW
          6FY1hRhGFgVqJ1w8qhJvGqwYpp9PSldsEzTPiJJakSQgH4UpVLnX1Jxjp9zqBDxbL9HJC
          FG33LDt+e3XcmcnaubVautNpdG8Nf5/R9/pCYV+ozYZaH7oULyTR7PO1b1DLxk2tOMWx7
          swgDq9UrJ3/WN1zS+FxS0TaJ+L14ckXWEUvdFccAIGOKT6AUivNf1xAqdpAlygEUfT9Z/
          1uTOIonhdl2B01uQrxupuW1mLeYDycsvB+tUUwP8mP4NKyluYYYHbt3wucuuAFRdnrSMD
          FOpHgL5hCeFkCQ1OreuZ1sDrtt+KjlxdHEaxiA9int5asPMwRrULYtGJVcgWV0TlabxVE
          1Eu14+E27o0ISMoUOpMw4UxPkob+ztWOqGIii95t1Mv+8sbKKG0WbGP58z9CAbnfSoVcB
          VRAdEL9n/bAo4Dmx/QaqvSERatEj31dhmOpzuuluM01en2A+S113oYnfd888vY=
      
- job:
    name: update-gitea-mirrors
    run: .playbooks/update-gitea-mirrors.yaml
    secrets:
      - name: mirror_creds
        secret: gitea-mirror

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - ansible-lint
        - yamllint
        - flake8
    gate:
      jobs:
        - ansible-lint
        - yamllint
        - flake8
    periodic-hourly:
      jobs:
        - update-gitea-mirrors
