---
- name: Mirror all GitHub repositories of one organization to gitea
  hosts: all
  tasks:
    - name: Install Python
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop:
        - ensure-python
        - ensure-pip

    - name: Install PyGithub
      ansible.builtin.pip:
        name:
          - PyGithub
          - requests

    - name: Ensure all mirrors are configured
      no_log: true
      ansible.builtin.script:
        cmd: scripts/mirror.py
      args:
        chdir: "{{ zuul.project.src_dir }}"
        executeable: python3
      environment:
        GITHUB_PAT: "{{ mirror_creds.GITHUB_PAT }}"
        GITEA_TOKEN: "{{ mirror_creds.GITEA_TOKEN }}"
      changed_when: true
