---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: letsencrypt@osism.tech
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: secret-letsencrypt-staging
    solvers:
      - http01:
          ingress:
            class: public

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    email: letsencrypt@osism.tech
    server: https://acme-v02.api.letsencrypt.org/directory 
    privateKeySecretRef:
      name: secret-letsencrypt-production
    solvers:
      - http01:
          ingress:
            class: public
