---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: logs
  namespace: default
spec:
  version: 7.15.1
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
  http:
    tls:
      selfSignedCertificate:
        disabled: true

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-logs-es
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    kubernetes.io/ingress.class: public
spec:
  rules:
  - host: elasticsearch.services.osism.tech
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: logs-es-http
            port:
              number: 9200
