---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: logs
  namespace: default
spec:
  version: 7.15.1
  count: 1
  elasticsearchRef:
    name: logs
  http:
    tls:
      selfSignedCertificate:
        disabled: true

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-logs-kb
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    kubernetes.io/ingress.class: public
spec:
  rules:
  - host: kibana.services.osism.tech
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: logs-kb-http
            port:
              number: 5601
